### ISSUE TITLE
Python 3.10.4 üzerinde kurulum hatası 

### ISSUE THREAD

**Issue by risedangel** [olcaytaner/TurkishMorphologicalAnalysis-Py#3]
Python 3.10.4 te, pip üzerinden install ile veya Github dan indirilen kodun local de 'python -m setup.py install' komutuyla kurulumu esnasında aşağıdaki hatayı alıyorum.Github dan indirdiğim repoda, 'C:\Users\<kullanici.adi>\Downloads\TurkishMorphologicalAnalysis-Py-master'  konumunda bulunan Readme.md dosyasının içini boşalttığım zaman kurulumu başarıyla gerçekleştirebildim. Sanırım normalde utf-8 kodlanmış belge, cp-1254 kodlaması ile okunmaya çalışılıyor. Okuma hatası kurulumu durduruyor.
`C:\Users\<kullanici.adi>\Downloads\TurkishMorphologicalAnalysis-Py-master>python -m setup.py install
Traceback (most recent call last):
  File "C:\Users\<kullanici.adi>\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\<kullanici.adi>\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\<kullanici.adi>\Downloads\TurkishMorphologicalAnalysis-Py-master\setup.py", line 5, in <module>
    long_description = (this_directory / "README.md").read_text()
  File "C:\Users\<kullanici.adi>\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1133, in read_text
    return f.read()
  File "C:\Users\<kullanici.adi>\AppData\Local\Programs\Python\Python310\lib\encodings\cp1254.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 755: character maps to <undefined>`

**Comment by olcaytaner** [comment]
Yeni versiyonda readme.md dosyası şimdi utf-8 ile okunuyor. Readme.md içeriğini boşaltmadan bir dener misiniz?

**Comment by olcaytaner** [comment]
Düzeltilme yapıldı.

**Comment by risedangel** [comment]
Aynı konfigürasyonda pip üzerinden kurulumu başarıyla gerçekleştirebildim. Emeğinize sağlık
